#imports
import os
import ProjectMacro
#getting local scons environment
Import('env')
localenv = env.Clone()

#explicit links
#localenv["LIBS"] = [
#	'dl',
#	'nsl',
#]
#adding OS specific libs
#localenv['LIBS'].extend(localenv['OSDependentLibs'])
localenv.Append(LIBS=['main_library'], LIBPATH=['#main_library'])

#building Binary
p = localenv.Program(os.path.join(localenv['PROJECT_BINARY_DIR'],'run_app'), Glob('*.cpp'))

Default(p)
