#imports
import os
import ProjectMacro
#getting local scons environment
Import('env')
localenv = env.Clone()

#explicit links
localenv["LIBS"] = [
	'boost_thread',
	'boost_date_time',
	'boost_system',
]

#https://o440.wordpress.com/2011/02/25/scons-and-code-coverage/
localenv.Append(CCFLAGS = ['-fprofile-arcs', '-ftest-coverage'])
localenv.Append(LIBS = ['gcov'])

#adding OS specific libs
#localenv['LIBS'].extend(localenv['OSDependentLibs'])
localenv.Append(LIBS=['main_library'], LIBPATH=['#main_library'])

localenv.MergeFlags([
	'-Wl,-rpath=' + localenv['LIBRARY_OUTPUT_PATH'],
])

#building Binary
p = localenv.Program(os.path.join(localenv['PROJECT_BINARY_DIR'],'run_app'), Glob('*.cpp'))

Default(p)
