repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
#    -   id: autopep8-wrapper
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
        exclude: >
                  (?x)^(
                      clean.bat|
                      build.bat
                  )$
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
    -   id: check-symlinks
    -   id: debug-statements
    -   id: detect-private-key
        exclude: >
                  (?x)^(
                      roles/jenkins-master/defaults/main.yml|
                      roles/jenkins-master/README.md
                  )$
    -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: requirements-txt-fixer
    -   id: sort-simple-yaml
#    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
-   repo: https://gitlab.com/pycqa/flake8
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: flake8
        args: [--max-line-length=120]
-   repo: https://github.com/pre-commit/pre-commit.git
    rev: v2.1.1
    hooks:
    -   id: validate_manifest
-   repo: https://github.com/asottile/reorder_python_imports.git
    rev: v2.0.0
    hooks:
    -   id: reorder-python-imports
#        language_version: python2.7
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.0.1
    hooks:
    -   id: add-trailing-comma
#-   repo: meta
#    hooks:
#    -   id: check-hooks-apply
#    -   id: check-useless-excludes
#-   repo: https://github.com/willthames/ansible-lint.git
#    sha: v3.4.20
#    hooks:
#    -   id: ansible-lint
#        files: \.(yaml|yml)$
-   repo: git://github.com/doublify/pre-commit-hindent
    rev: b3680b6ebf9f7cf29b19307f246adef66756feef
    hooks:
    -   id: hindent
-   repo: git://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
    - id: shell-lint
#-   repo: git://github.com/doublify/pre-commit-clang-format
#    sha: 994f99b6498e9c76341367ecaf76c69dfb4ea4f2
#    hooks:
#    -   id: clang-format
