# Copyright Alban Andrieu 2013-2017
# Distributed under the GPL-3.0
# (See accompanying file LICENSE.md)

language: cpp
sudo: required
dist: travis_lts
#dist: bionic

python:
#  - 2.7
#  - 3.3
#  - 3.4
#  - 3.5
  - 3.6
#  - 3.7

virtualenv:
  system_site_packages: false

# Do not build branches of the form "pr/*". By prefixing pull requests coming
# from branches inside the repository with pr/, this avoids building both the
# branch push _and_ the pull request.
branches:
#  except: /pr\/.*/
  only:
  - master

env:
  global:
    - PROJECT_SRC="$TRAVIS_BUILD_DIR"
    - WORKSPACE="$TRAVIS_BUILD_DIR"
    - SONAR_CMD=""
#    - SONARQUBE_SKIPPED=true
    - MAKE=make
    - ARCH=linux

addons:
  apt:
    packages:
      - unzip
      # Java8 Required for Sonar and SQLCL
      - oracle-java8-installer
      - oracle-java8-set-default
  sonarcloud:
    organization: albanandrieu-github
    token:
      secure: "m3pCsPSu3M39JP+8f+WALyDOxRpq2PJERIuyvK/XKVwyvC4hNT/SLIKQayLCAgPzYSEeqRchORr2Y8wKrRHMblfZtZu9XKVdv1cvBe26NHjKZy7xakuvi/7kvKI/Yu22DAcE1a6mBz1XC5WPUiRIm+vm3X4VzWBV6/Y+ptst6o8="
    branches:
      - master
      - develop

cache:
  pip: true
  directories:
    - $HOME/.sonar/cache
    - $HOME/.cache
    - $HOME/.m2
    - node_modules
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.6.2
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.7.1
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.8.0
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.9.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.59.0
    - ${TRAVIS_BUILD_DIR}/depgit pushs/boost-1.60.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.61.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.62.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.63.0

install:
 # Install conan
 # - pip install --upgrade pip
 - sudo pip install conan==1.21.1
 #- sudo pip2.7 install -r requirements-current-2.7.txt
 # Automatic detection of your arch, compiler, etc.
 - conan user

script:
  - mkdir -p sample/build-${ARCH}/
  - cd sample/build-${ARCH}/
#  - ./build.sh
  # Download dependencies, build, test and create package
  - conan remote add nabla https://api.bintray.com/conan/bincrafters/public-conan
  - conan user -r nabla albanandrieu
  - conan install ../microsoft/ --build boost_system
  - export CMAKE_INSTALL_PREFIX=$PROJECT_SRC/sample/build-${ARCH}/target/
  #- export CMAKE_INSTALL_PREFIX=/usr/local/
  - cmake ${CMAKEFLAGS} -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX} -DCMAKE_CXX_COMPILER=${CXX} ../../sample/microsoft/
  - make install
  - make CTEST_OUTPUT_ON_FAILURE=1 test
  - make package
#  - sonar-scanner

services:
  - docker

matrix:
  include:
    #- compiler: gcc
    #  os: osx
    #  before_script:
    #    - brew update
    #    - brew outdated cmake || brew upgrade cmake
    #  env: CMAKEFLAGS="-DWITH_BOOST=ON -DHAS_MEMRCHR=OFF" CXX=g++
    #- compiler: clang
    #  os: osx
    #  before_script:
    #    - brew update
    #    - brew outdated cmake || brew upgrade cmake
    #  env: CMAKEFLAGS="-DWITH_BOOST=ON -DHAS_MEMRCHR=OFF" CXX=clang++
    #- compiler: gcc
    #  os: linux
    #  dist: precise
    #  sudo: false
    #  addons:
    #    apt:
    #      sources:
    #        - george-edison55-precise-backports
    #      packages:
    #        - cmake
    #        - cmake-data
    #        - libboost-system-dev
    #        - libboost-filesystem-dev
    #  env: CMAKEFLAGS="-DWITH_BOOST=ON" CXX=g++-4.6
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - colormake
            - libxml2-dev
            - libxml2-utils
            - libcppunit-dev
            - libboost-thread-dev
            - libboost-date-time-dev
            - libboost-filesystem-dev
      env: CMAKEFLAGS="-DWITH_BOOST=ON" CXX=g++-4.8.4
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - cmake
            - colormake
            - libxml2-dev
            - libxml2-utils
            - libcppunit-dev
            - libboost-thread-dev
            - libboost-date-time-dev
            - libboost-filesystem-dev
      env: CMAKEFLAGS="-DWITH_BOOST=ON" CXX=g++-4.9
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
            - colormake
            - libxml2-dev
            - libxml2-utils
            - libcppunit-dev
            - libboost-thread-dev
            - libboost-date-time-dev
            - libboost-filesystem-dev
      env: CMAKEFLAGS="-DWITH_BOOST=OFF" CXX=g++-5
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cmake
            - colormake
            - libxml2-dev
            - libxml2-utils
            - libcppunit-dev
            - libboost-thread-dev
            - libboost-date-time-dev
            - libboost-filesystem-dev
      env: CMAKEFLAGS="-DWITH_BOOST=OFF" CXX=g++-6
    - compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - cmake
            - libcppunit-dev
            - libxml2-dev
            - libxml2-utils
            - libboost-thread-dev
            - libboost-date-time-dev
            - libboost-filesystem-dev
      env: CMAKEFLAGS="-DWITH_BOOST=ON" CXX=clang++-3.6
    - compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - cmake
            - libcppunit-dev
            - libxml2-dev
            - libxml2-utils
            - libboost-thread-dev
            - libboost-date-time-dev
            - libboost-filesystem-dev
      env: CMAKEFLAGS="-DWITH_BOOST=ON" CXX=clang++-3.7
