# Copyright Louis Dionne 2013-2017
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.md or copy at http://boost.org/LICENSE_1_0.txt)

language: c++
sudo: required
dist: trusty

# Do not build branches of the form "pr/*". By prefixing pull requests coming
# from branches inside the repository with pr/, this avoids building both the
# branch push _and_ the pull request.
branches:
  except: /pr\/.*/

env:
  global:
    - PROJECT_SRC="$TRAVIS_BUILD_DIR"
    - WORKSPACE="$TRAVIS_BUILD_DIR"    
#    - SONAR_PROCESSOR="x86-64"
    - SONAR_CMD=""
    - MAKE=make
    - ARCH=linux
addons:
  apt:
    packages:
      - valgrind
#      - g++-6
      - libcppunit-dev
      - colormake
      - libxml2-dev
      - libxml2-utils
      - libboost-filesystem-dev
    sources: &sources
      - ubuntu-toolchain-r-test

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.6.2
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.7.1
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.8.0
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.9.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.59.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.60.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.61.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.62.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.63.0

script:
  - mkdir -p sample/build-${ARCH}/
  - cd sample/build-${ARCH}/
#  - ./build.sh
  - cmake ${CMAKEFLAGS} -DCMAKE_CXX_COMPILER=${CXX} ../../sample/microsoft/
  - make
  - make CTEST_OUTPUT_ON_FAILURE=1 test
  - make package

matrix:
  include:
    #- compiler: gcc
    #  os: osx
    #  before_script:
    #    - brew update
    #    - brew outdated cmake || brew upgrade cmake
    #  env: CMAKEFLAGS="-DWITH_BOOST=ON -DHAS_MEMRCHR=OFF" CXX=g++
    #- compiler: clang
    #  os: osx
    #  before_script:
    #    - brew update
    #    - brew outdated cmake || brew upgrade cmake
    #  env: CMAKEFLAGS="-DWITH_BOOST=ON -DHAS_MEMRCHR=OFF" CXX=clang++
    #- compiler: gcc
    #  os: linux
    #  dist: precise
    #  sudo: false
    #  addons:
    #    apt:
    #      sources:
    #        - george-edison55-precise-backports
    #      packages:
    #        - cmake
    #        - cmake-data
    #        - libboost-system-dev
    #        - libboost-filesystem-dev
    #  env: CMAKEFLAGS="-DWITH_BOOST=ON" CXX=g++-4.6
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
#            - g++-4.8.2
#            - cmake
            - libboost-system-dev
            - libboost-filesystem-dev
            - libcppunit-dev
      env: CMAKEFLAGS="-DWITH_BOOST=ON" CXX=g++-4.8.2
    #- compiler: gcc
    #  os: linux
    #  addons:
    #    apt:
    #      sources:
    #        - ubuntu-toolchain-r-test
    #      packages:
    #        - g++-4.9
    #        - cmake
    #        - libboost-system-dev
    #        - libboost-filesystem-dev
    #  env: CMAKEFLAGS="-DWITH_BOOST=ON" CXX=g++-4.9
    #- compiler: gcc
    #  os: linux
    #  addons:
    #    apt:
    #      sources:
    #        - ubuntu-toolchain-r-test
    #      packages:
    #        - g++-5
    #        - cmake
    #  env: CMAKEFLAGS="-DWITH_BOOST=OFF" CXX=g++-5
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cmake
            - libboost-system-dev
            - libboost-filesystem-dev
            - libcppunit-dev            
      env: CMAKEFLAGS="-DWITH_BOOST=OFF" CXX=g++-6
    #- compiler: clang
    #  os: linux
    #  addons:
    #    apt:
    #      sources:
    #        - ubuntu-toolchain-r-test
    #        - llvm-toolchain-precise-3.6
    #      packages:
    #        - clang-3.6
    #        - cmake
    #        - libboost-system-dev
    #        - libboost-filesystem-dev
    #  env: CMAKEFLAGS="-DWITH_BOOST=ON" CXX=clang++-3.6
    - compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - cmake
            - libboost-system-dev
            - libboost-filesystem-dev
            - libcppunit-dev
      env: CMAKEFLAGS="-DWITH_BOOST=ON" CXX=clang++-3.7
