#!/bin/sh
#Generated by scons
export LIBPATH=/workspace/users/albandri10/cpp/target/lib/x86Linux/debug64:/workspace/users/albandri10/cpp/target/lib/x86Linux/debug64/shared:/usr/lib/jvm/java-7-oracle/jre/lib/amd64/server
