#imports
import os
import ProjectMacro
#getting local scons environment
Import('env')
localenv = env.Clone()

#explicit links
localenv["LIBS"] = [
	'cppunit',
]

#shared_lib = SConscript('../cpp/SConscript')
#localenv.Append( LIBS=[shared_lib] )

#adding OS specific libs
#localenv['LIBS'].extend(localenv['OSDependentLibs'])
localenv.Append(LIBS=['test_library'], LIBPATH=['#test_library'])

#building Binary
p = localenv.Program(os.path.join(localenv['PROJECT_BINARY_DIR'],'run_tests'), Glob('*.cpp'))

Default(p)
