#imports
import os
import ProjectMacro
#getting local scons environment
Import('env')
localenv = env.Clone()

#exporting headers
localenv.Install(os.path.join(localenv['PROJECT_INCLUDE_DIR'],''), Glob('include/*.h')+Glob('include/*.ipp'))

#building shared library
p = localenv.SharedLibrary(os.path.join(localenv['PROJECT_INCLUDE_DIR'],'main_library'), Glob('*.cpp'))

Default(p)
